version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "80:5173"  # Exposing Vite's dev server on port 80
    volumes:
      - ./app:/project/app  # Sync app directory for live updates
      - /project/app/node_modules  # Ensure node_modules doesn't get overridden
    env_file:
      - ./app/.env  # Load environment variables from app/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5555:5555"
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=michael_forums
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: