type MessageMutation {
    createForum(title: String!, about: String!): Forum!
    editForum(id: ID!, title: String!, about: String!): Void
    deleteForum(id: ID!): Void

    createPost(forumId: ID!, title: String!, content: String!): Post!
    editPost(id: ID!, title: String!, content: String!): Void
    deletePost(id: ID!): Void

    createReply(postId: ID!, content: String!): Reply!
    editReply(id: ID!, content: String!): Void
    deleteReply(id: ID!): Void
}