mutation CreatePost($forumId: ID!, $title: String!, $content: String!) {
  messageMutation {
    createPost(forumId: $forumId, title: $title, content: $content) {
      id
    }
  }
}

mutation CreateReply($postId: ID!, $content: String!) {
  messageMutation {
    createReply(postId: $postId, content: $content) {
      id
    }
  }
}