query GetForums($currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getForums(currentPage: $currentPage, pageSize: $pageSize) {
      id
      title
      about
    }
  }
}

query GetForum($id: ID!, $currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getForum(id: $id) {
      id
      title
      about
      posts(currentPage: $currentPage, pageSize: $pageSize) {
        id
        title
        authorName
      }
    }
  }
}

query GetPost($id: ID!, $currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getPost(id: $id) {
      id
      title
      content
      authorName
      forumId

      replies(currentPage: $currentPage, pageSize: $pageSize) {
        id
        content
        authorName
      }
    }
  }
}