fragment ForumFields on Forum {
  id
  title
  about
}

fragment PostFields on Post {
  id
  title
  authorName
  authorId
  createdAt
  updatedAt
}

fragment ReplyFields on Reply {
  id
  content
  authorName
  authorId
  createdAt
  updatedAt
}

query GetForums($currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getForums(currentPage: $currentPage, pageSize: $pageSize) {
      ...ForumFields
    }
  }
}

query GetForum($id: ID!, $currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getForum(id: $id) {
      ...ForumFields
      posts(currentPage: $currentPage, pageSize: $pageSize) {
        ...PostFields
      }
    }
  }
}

query GetPost($id: ID!, $currentPage: Int!, $pageSize: Int!) {
  messageQuery {
    getPost(id: $id) {
      ...PostFields
      content
      forumId

      replies(currentPage: $currentPage, pageSize: $pageSize) {
        ...ReplyFields
      }
    }
  }
}