type RootMutation {
    userMutation: UserMutation
    messageMutation: MessageMutation
}

type RootQuery {
    user: User,
    userQuery: UserQuery,
    forum: Forum,
    post: Post,
    messageQuery: MessageQuery,
}

schema {
  query: RootQuery
  mutation: RootMutation
}